name: UI client CI/CD

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
      - name: Install dependencies
        run: npm install
      - name: Cache node_modules
        uses: actions/cache/save@v3
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

#  TODO: configure
  test:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: It is the place for running the tests
        run: echo Unit tests

  deploy:
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Use cached node_modules
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: npm run deploy:prod
